//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakeWinForms.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SnakeWinForms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1000000000000000000000001
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///1111111111100000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000222200000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000111111111111        /// [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string TestLevel {
            get {
                return ResourceManager.GetString("TestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1111111111111111111111111
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1111111111100000000000001
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///0000000000000000000000000
        ///1000000000222200000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1000000000000000000000001
        ///1111111111111111111111111.
        /// </summary>
        public static string TestLevel1 {
            get {
                return ResourceManager.GetString("TestLevel1", resourceCulture);
            }
        }
    }
}
